version: "3"

tasks:
  compile:
    desc: "Compile go application"
    cmds:
      - GOOS=linux GOARCH=386 go build -o bin/go-tutorial-linux-386 main.go
      - GOOS=linux GOARCH=amd64 go build -o bin/go-tutorial-amd64-linux main.go
      - GOOS=windows GOARCH=386 go build -o bin/go-tutorial-windows-386.exe main.go
      - GOOS=windows GOARCH=amd64 go build -o bin/go-tutorial-windows-amd64.exe main.go
      - GOOS=darwin GOARCH=amd64 go build -o bin/go-tutorial-amd64-darwin main.go
      - GOOS=js GOARCH=wasm go build -o bin/go-tutorial-wasm.wasm main.go
    silent: true

  clean:
    desc: "Clean go application"
    cmds:
      - go clean
      - rm -rf bin/*
    silent: true

  build:
    desc: "Build go application"
    cmds:
      - go build -o bin/go-tutorial main.go
    silent: true

  docker_build:
    desc: "Docker build go application"
    cmds:
      - docker build -t go-tutorial -f Dockerfile
    silent: true

  docker_run:
    desc: "Run docker container go application"
    cmds:
      - docker run -d --name go-tutorial go-tutorial
    silent: true

  run:
    desc: "Run go application"
    cmds:
      - go run main.go
    silent: true

  preview:
    desc: "Run go application"
    cmds:
      - ./bin/go-tutorial
    silent: true

  push:
    desc: "git push go application"
    cmds:
      - git add . && git commit -m "update taskfile cmd" && git push
    silent: true

  test_banana:
    desc: "test banana go application"
    cmds:
      - go test banana/banana_test.go -v
    silent: true

  test_hello:
    desc: "test hello go application"
    cmds:
      - go test hello/hello_test.go -v
    silent: true

  test_date:
    desc: "test date go application"
    cmds:
      - go test date/date_test.go -v
    silent: true

  test_spread:
    desc: "test spread operator go application"
    cmds:
      - go test operators/spread/spread_test.go -v
    silent: true

  test_all:
    desc: "test all cases go application"
    cmds:
      - go test ./... -v
    silent: true
